<html lang="en">
    <head>
        <link href="/js/node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" type="text/css">
	<style type="text/css">
		#test{
			/*background:red;*/
		}
		table {
			width: 100%;
			border: 1px solid #DDD;
			margin-bottom: 8px;
		}
		
		table th {
			background: #DDD;
			padding: 8px;
		}

		table td {
			border:1px solid #ddd;
		}
		table td.label {
			background: #DDD;
		}
		
		table.process th {
		}
		table.process td {
		}
		table.version {
		}

		ul {
		}
		ul.operations {
		}
		ul.operations li {
		}
		ul.errors {
			list-style:none;
		}
		ul.errors li {
		}
		ul.reasons {
			list-style:none;
		}
		ul.reasons li {
		}
		ul.influences {
			list-style:none;
		}
		ul.simulations,
		ul.simulations ul {
			list-style:none;
		}
		ul.reasons li p, 
		ul.influences li p,
		ul.simulations li p {
		}
		
	</style>
	</head>
	<body>

<h2><?php echo $this->entity; ?>. <small>nº<?php echo $this->entity->getNumber(); ?></small></h2>

<table class="process">
	<tbody>
		<tr>
			<td class="label"><b>Complexity</b></td>
			<td> <?php echo $this->entity->getComplexity()->getName(); ?></td>
			<td class="label"><b>Customer</b></td>
			<td colspan="3"><?php echo $this->entity->getCustomer()->getName(); ?></td>
		</tr>
		<tr>
			<td class="label"><b>Productive plan</b></td>
			<td> <?php echo $this->entity->getPlant()->getName(); ?></td>
			<td class="label"><b>Machine</b></td>
			<td><?php echo $this->entity->getMachine()->getName(); ?></td>
			<td class="label"><b>Line</b>
			<td><?php echo $this->entity->getLine(); ?></td>
		</tr>
		<?php if (null !== ($desc = $this->entity->getBody())) : ?>
			<tr>
				<td colspan="6">
					<!--<b>Description</b>-->
					<?php echo $desc; ?>
				</td>
			</tr>
		<?php endif; ?>
	</tbody>
</table>

<?php foreach ($this->entity->getVersions() as $version) : ?>
<table>
	<thead>
		<tr>
			<th colspan="<?php echo $version->getStages()->count(); ?>">
				<?php echo $version->getName(); ?>
			</th>
		</tr>
	</thead>
	<tbody>
		<?php if (null !== ($desc = $version->getDescription())) : ?>
			<tr>
				<td colspan="<?php echo $version->getStages()->count(); ?>">
					<b>Description</b>
					<?php echo $version->getDescription(); ?>
				</td>
			</tr>
		<?php endif; ?>
		<tr>
		<?php foreach ($version->getStages() as $stage) : ?>
			<td align="center" class="label">
				Stage <?php echo $stage->getOrder(); ?>
			</td>
		<?php endforeach ?>
		</tr>
		<tr>
		<?php foreach ($version->getStages() as $stage) : ?>
			<td align="center">
				<?php if ($stage->hasImage()) : ?>
				<img src="<?php echo $stage->getImage()->getName(); ?>" width="100" height="180"/>
				<?php endif; ?>
			</td>
		<?php endforeach ?>
		</tr>
		<tr>
		<?php foreach ($version->getStages() as $stage) : ?>
			<td valign="top">
				<!--
					<?php if (null !== ($desc = $stage->getBody())): ?><b>Description</b><?php endif; ?>
				-->
				<?php echo $stage->getBody(); ?>
			</td>
		<?php endforeach ?>
		</tr>
		<tr>
			<td colspan="<?php echo $version->getStages()->count(); ?>" class="label">
				<b>Operations</b>
			</td>
		</tr>
		<tr>
		<?php foreach ($version->getStages() as $stage) : ?>
			<td class="">
				<ul>
				<?php foreach ($stage->getOperations() as $op): ?>
					<li><?php echo $op->getLongName(); ?></li>
				<?php endforeach ?>
				</ul>
			</td>
		<?php endforeach ?>
		</tr>
		<tr>
			<td colspan="<?php echo $version->getStages()->count(); ?>" class="label">
				<b>Errors</b>
			</td>
		</tr>
		<tr>
		<?php foreach ($version->getStages() as $stage) : ?>
			<td valign="top">
				<ul class="errors">
				<?php foreach ($stage->getHints() as $error): ?>
					<li><?php echo $error->getName(); ?></li>
					<?php if (!$error->getReasons()->isEmpty()) : ?>
						<ul class="reasons">
						<?php foreach ($error->getReasons() as $r => $reason): ?>
							<li>
								<small>Reason <?php echo $r+1; ?></small>
							</li>
							<?php foreach ($reason->getNotes() as $note): ?>
								<li><?php echo $note->getText(); ?></li>
							<?php endforeach ?>
							<?php if (!$reason->getInfluences()->isEmpty()) : ?>
								<ul class="influences">
								<?php foreach ($reason->getInfluences() as $i => $influence) : ?>
									<li>
										<small>Influence <?php echo $r+1; ?>.<?php echo $i+1; ?></small>
									</li>
									<?php foreach ($influence->getNotes() as $note): ?>
										<li><?php echo $note->getText(); ?></li>
									<?php endforeach ?>
									<?php if (!$influence->getSimulations()->isEmpty()) : ?>
										<ul class="simulations">
										<?php foreach ($influence->getSimulations() as $s => $simulation) : ?>
											<li>
												<small>Simulation <?php echo $r+1; ?>.<?php echo $i+1; ?>.<?php echo $s+1; ?></small>
												<?php if (!$simulation->getSuggestions()->isEmpty()) : ?>
												<ul>
													<small>Suggestions</small>
													<?php foreach ($simulation->getSuggestions() as $note) : ?>
														<li><?php echo $note->getText(); ?></li>
													<?php endforeach; ?>
												</ul>
												<?php endif; ?>
												<?php if (!$simulation->getEffects()->isEmpty()) : ?>
												<ul>
													<small>Effects</small>
													<?php foreach ($simulation->getEffects() as $note) : ?>
														<li><?php echo $note->getText(); ?></li>
													<?php endforeach; ?>
												</ul>
												<?php endif; ?>
												<?php if (!$simulation->getPreventions()->isEmpty()) : ?>
												<ul>
													<li><small>Preventions</small></li>
													<?php foreach ($simulation->getPreventions() as $note) : ?>
														<li><?php echo $note->getText(); ?></li>
													<?php endforeach; ?>
												</ul>
												<?php endif; ?>
											</li>
										<?php endforeach; ?>	
										</ul>
									<?php endif ?>
								<?php endforeach ?>
								</ul>
							<?php endif ?>
						<?php endforeach ?>
						</ul>
					<?php endif ?>
				<?php endforeach ?>
				</ul>
			</td>
		<?php endforeach ?>
		</tr>
	</tbody>
</table>
<?php endforeach ?>
	</body>
</html>
