<?php echo $this->form()->openTag($form) ?>
	<dl class="zend_form">
        <?php foreach ($form as $element): ?>
			<div class="form-group">
				<?php $class = "form-control"; ?>
				<?php if ($element instanceof Zend\Form\Element\Button) : ?>
					<?php $class .= ' btn btn-primary'; ?>
				<?php endif; ?>
				<?php $element->setAttribute('class', $class); ?>
            	<?php if ($element->getLabel() != null && !$element instanceof Zend\Form\Element\Button): ?>
            	    <dt><?php echo $this->formLabel($element) ?></dt>
            	<?php endif ?>
				<dd><?php echo $this->formElement($element) . $this->formElementErrors($element) ?></dd>
			</div>
        <?php endforeach ?>
    </dl>
<?php if ($this->redirect): ?>
    <input type="hidden" name="redirect" value="<?php echo $this->redirect ?>">
<?php endif ?>
<?php echo $this->form()->closeTag() ?>
